name: Build Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build-backend:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build backend
        working-directory: backend
        run: ./gradlew clean bootJar --no-daemon