name: Build Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build